/* eslint-disable */
// AUTO-GÉNÉRÉ par scripts/gen-types.mjs à partir de supabase/migrations — ne pas modifier à la main.
// Régénérer : npm run types:gen   (la CI vérifie avec npm run types:check)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      activities: {
        Row: {
          id: string;
          client_id: string | null;
          lead_id: string | null;
          activity_type: "CLIENT_CREATED" | "QUOTE_CREATED" | "QUOTE_SENT" | "QUOTE_ACCEPTED" | "INTERVENTION_CREATED" | "INTERVENTION_COMPLETED" | "PHOTO_UPLOADED" | "INVOICE_CREATED" | "PAYMENT_RECEIVED" | "LEAD_CONVERTED" | "NOTE_ADDED" | "STATUS_CHANGED";
          title: string;
          description: string | null;
          metadata: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          lead_id?: string | null;
          activity_type: "CLIENT_CREATED" | "QUOTE_CREATED" | "QUOTE_SENT" | "QUOTE_ACCEPTED" | "INTERVENTION_CREATED" | "INTERVENTION_COMPLETED" | "PHOTO_UPLOADED" | "INVOICE_CREATED" | "PAYMENT_RECEIVED" | "LEAD_CONVERTED" | "NOTE_ADDED" | "STATUS_CHANGED";
          title: string;
          description?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          lead_id?: string | null;
          activity_type?: "CLIENT_CREATED" | "QUOTE_CREATED" | "QUOTE_SENT" | "QUOTE_ACCEPTED" | "INTERVENTION_CREATED" | "INTERVENTION_COMPLETED" | "PHOTO_UPLOADED" | "INVOICE_CREATED" | "PAYMENT_RECEIVED" | "LEAD_CONVERTED" | "NOTE_ADDED" | "STATUS_CHANGED";
          title?: string;
          description?: string | null;
          metadata?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      app_settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          key: string;
          value: Json;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          key?: string;
          value?: Json;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: number;
          occurred_at: string;
          actor_id: string | null;
          actor_role: string | null;
          table_name: string;
          record_id: string | null;
          action: string;
          changes: Json;
        };
        Insert: {
          id?: number;
          occurred_at?: string;
          actor_id?: string | null;
          actor_role?: string | null;
          table_name: string;
          record_id?: string | null;
          action: string;
          changes?: Json;
        };
        Update: {
          id?: number;
          occurred_at?: string;
          actor_id?: string | null;
          actor_role?: string | null;
          table_name?: string;
          record_id?: string | null;
          action?: string;
          changes?: Json;
        };
        Relationships: [];
      };
      client_installations: {
        Row: {
          id: string;
          client_id: string;
          label: string | null;
          hood_length: string | null;
          hood_type: string | null;
          filter_count: number | null;
          filter_type: string | null;
          duct_present: boolean | null;
          duct_length: string | null;
          duct_accessibility: string | null;
          motor_present: boolean | null;
          motor_type: string | null;
          motor_accessibility: string | null;
          night_intervention: boolean | null;
          schedule_preference: string | null;
          soil_level: string | null;
          remarks: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          label?: string | null;
          hood_length?: string | null;
          hood_type?: string | null;
          filter_count?: number | null;
          filter_type?: string | null;
          duct_present?: boolean | null;
          duct_length?: string | null;
          duct_accessibility?: string | null;
          motor_present?: boolean | null;
          motor_type?: string | null;
          motor_accessibility?: string | null;
          night_intervention?: boolean | null;
          schedule_preference?: string | null;
          soil_level?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          label?: string | null;
          hood_length?: string | null;
          hood_type?: string | null;
          filter_count?: number | null;
          filter_type?: string | null;
          duct_present?: boolean | null;
          duct_length?: string | null;
          duct_accessibility?: string | null;
          motor_present?: boolean | null;
          motor_type?: string | null;
          motor_accessibility?: string | null;
          night_intervention?: boolean | null;
          schedule_preference?: string | null;
          soil_level?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          reference: string | null;
          lead_id: string | null;
          company_name: string;
          contact_name: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          postal_code: string | null;
          siret: string | null;
          business_type: string | null;
          status: "active" | "inactive" | "archived";
          notes: string | null;
          next_action: string | null;
          next_action_date: string | null;
          assigned_user: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          reference?: string | null;
          lead_id?: string | null;
          company_name: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          siret?: string | null;
          business_type?: string | null;
          status?: "active" | "inactive" | "archived";
          notes?: string | null;
          next_action?: string | null;
          next_action_date?: string | null;
          assigned_user?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          reference?: string | null;
          lead_id?: string | null;
          company_name?: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          siret?: string | null;
          business_type?: string | null;
          status?: "active" | "inactive" | "archived";
          notes?: string | null;
          next_action?: string | null;
          next_action_date?: string | null;
          assigned_user?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      credit_notes: {
        Row: {
          id: string;
          number: string;
          invoice_id: string;
          client_id: string;
          issued_at: string;
          reason: string;
          subtotal_ht: number;
          discount_ht: number;
          vat_amount: number;
          total_ttc: number;
          lines: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          number: string;
          invoice_id: string;
          client_id: string;
          issued_at?: string;
          reason: string;
          subtotal_ht: number;
          discount_ht?: number;
          vat_amount: number;
          total_ttc: number;
          lines?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          number?: string;
          invoice_id?: string;
          client_id?: string;
          issued_at?: string;
          reason?: string;
          subtotal_ht?: number;
          discount_ht?: number;
          vat_amount?: number;
          total_ttc?: number;
          lines?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      document_counters: {
        Row: {
          key: string;
          value: number;
        };
        Insert: {
          key: string;
          value?: number;
        };
        Update: {
          key?: string;
          value?: number;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          client_id: string;
          doc_type: "quote" | "invoice" | "report" | "contract" | "photo" | "other";
          title: string;
          storage_path: string;
          mime_type: string | null;
          size_bytes: number | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          doc_type?: "quote" | "invoice" | "report" | "contract" | "photo" | "other";
          title: string;
          storage_path: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          doc_type?: "quote" | "invoice" | "report" | "contract" | "photo" | "other";
          title?: string;
          storage_path?: string;
          mime_type?: string | null;
          size_bytes?: number | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      electronic_invoice_documents: {
        Row: {
          id: string;
          invoice_id: string;
          format: string;
          status: string;
          payload: Json;
          transmitted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          format?: string;
          status?: string;
          payload?: Json;
          transmitted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          format?: string;
          status?: string;
          payload?: Json;
          transmitted_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      intervention_photos: {
        Row: {
          id: string;
          intervention_id: string;
          client_id: string;
          kind: "before" | "after" | "technical";
          storage_path: string;
          comment: string | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          intervention_id: string;
          client_id: string;
          kind: "before" | "after" | "technical";
          storage_path: string;
          comment?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          intervention_id?: string;
          client_id?: string;
          kind?: "before" | "after" | "technical";
          storage_path?: string;
          comment?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      intervention_products: {
        Row: {
          id: string;
          intervention_id: string;
          name: string;
          category: string | null;
          quantity: number;
          unit: string;
          unit_cost: number;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          intervention_id: string;
          name: string;
          category?: string | null;
          quantity?: number;
          unit?: string;
          unit_cost?: number;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          intervention_id?: string;
          name?: string;
          category?: string | null;
          quantity?: number;
          unit?: string;
          unit_cost?: number;
          notes?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      intervention_reports: {
        Row: {
          id: string;
          intervention_id: string;
          work_completed: string | null;
          observations: string | null;
          difficulties: string | null;
          recommendations: string | null;
          checklist: Json;
          provider_signature: string | null;
          client_signature: string | null;
          validated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          intervention_id: string;
          work_completed?: string | null;
          observations?: string | null;
          difficulties?: string | null;
          recommendations?: string | null;
          checklist?: Json;
          provider_signature?: string | null;
          client_signature?: string | null;
          validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          intervention_id?: string;
          work_completed?: string | null;
          observations?: string | null;
          difficulties?: string | null;
          recommendations?: string | null;
          checklist?: Json;
          provider_signature?: string | null;
          client_signature?: string | null;
          validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      interventions: {
        Row: {
          id: string;
          reference: string | null;
          client_id: string;
          installation_id: string | null;
          provider_id: string | null;
          scheduled_date: string | null;
          time_slot: string | null;
          service_type: string | null;
          status: "to_plan" | "planned" | "in_progress" | "completed" | "cancelled";
          description: string | null;
          price_ht: number | null;
          notes: string | null;
          completed_at: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          quote_id: string | null;
          start_time: string | null;
          end_time: string | null;
          address: string | null;
        };
        Insert: {
          id?: string;
          reference?: string | null;
          client_id: string;
          installation_id?: string | null;
          provider_id?: string | null;
          scheduled_date?: string | null;
          time_slot?: string | null;
          service_type?: string | null;
          status?: "to_plan" | "planned" | "in_progress" | "completed" | "cancelled";
          description?: string | null;
          price_ht?: number | null;
          notes?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          quote_id?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          address?: string | null;
        };
        Update: {
          id?: string;
          reference?: string | null;
          client_id?: string;
          installation_id?: string | null;
          provider_id?: string | null;
          scheduled_date?: string | null;
          time_slot?: string | null;
          service_type?: string | null;
          status?: "to_plan" | "planned" | "in_progress" | "completed" | "cancelled";
          description?: string | null;
          price_ht?: number | null;
          notes?: string | null;
          completed_at?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          quote_id?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          address?: string | null;
        };
        Relationships: [];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          label: string;
          description: string | null;
          quantity: number;
          unit_price_ht: number;
          vat_rate: number;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          label: string;
          description?: string | null;
          quantity?: number;
          unit_price_ht?: number;
          vat_rate?: number;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          label?: string;
          description?: string | null;
          quantity?: number;
          unit_price_ht?: number;
          vat_rate?: number;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          number: string | null;
          client_id: string;
          quote_id: string | null;
          issued_at: string;
          due_at: string | null;
          status: "unpaid" | "partially_paid" | "paid" | "overdue" | "cancelled";
          notes: string | null;
          subtotal_ht: number;
          vat_amount: number;
          total_ttc: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          discount_ht: number;
          cancelled_at: string | null;
          cancellation_reason: string | null;
        };
        Insert: {
          id?: string;
          number?: string | null;
          client_id: string;
          quote_id?: string | null;
          issued_at?: string;
          due_at?: string | null;
          status?: "unpaid" | "partially_paid" | "paid" | "overdue" | "cancelled";
          notes?: string | null;
          subtotal_ht?: number;
          vat_amount?: number;
          total_ttc?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          discount_ht?: number;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
        };
        Update: {
          id?: string;
          number?: string | null;
          client_id?: string;
          quote_id?: string | null;
          issued_at?: string;
          due_at?: string | null;
          status?: "unpaid" | "partially_paid" | "paid" | "overdue" | "cancelled";
          notes?: string | null;
          subtotal_ht?: number;
          vat_amount?: number;
          total_ttc?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          discount_ht?: number;
          cancelled_at?: string | null;
          cancellation_reason?: string | null;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          reference: string | null;
          source: string;
          status: "new" | "contacted" | "qualified" | "quote_requested" | "quote_sent" | "won" | "lost";
          priority: string | null;
          company_name: string | null;
          contact_name: string | null;
          phone: string | null;
          email: string | null;
          business_type: string | null;
          city: string | null;
          postal_code: string | null;
          need_type: string | null;
          request_type: string | null;
          installation_type: string | null;
          hood_type: string | null;
          hood_length: string | null;
          filter_count: number | null;
          duct_present: boolean | null;
          duct_length: string | null;
          motor_present: boolean | null;
          soil_level: string | null;
          accessibility: string | null;
          night_intervention: boolean | null;
          schedule_preference: string | null;
          last_cleaning: string | null;
          requested_frequency: string | null;
          maintenance_frequency: string | null;
          urgency_level: string | null;
          preferred_contact: string | null;
          consent: boolean | null;
          photos: Json;
          message: string | null;
          notes: string | null;
          assigned_user: string | null;
          next_action: string | null;
          next_due_at: string | null;
          last_intervention_at: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          landing_page: string | null;
          service_source: string | null;
          zone_source: string | null;
          created_at: string;
          updated_at: string;
          next_action_date: string | null;
          converted_client_id: string | null;
          address: string | null;
          filter_type: string | null;
          motor_type: string | null;
        };
        Insert: {
          id?: string;
          reference?: string | null;
          source?: string;
          status?: "new" | "contacted" | "qualified" | "quote_requested" | "quote_sent" | "won" | "lost";
          priority?: string | null;
          company_name?: string | null;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          business_type?: string | null;
          city?: string | null;
          postal_code?: string | null;
          need_type?: string | null;
          request_type?: string | null;
          installation_type?: string | null;
          hood_type?: string | null;
          hood_length?: string | null;
          filter_count?: number | null;
          duct_present?: boolean | null;
          duct_length?: string | null;
          motor_present?: boolean | null;
          soil_level?: string | null;
          accessibility?: string | null;
          night_intervention?: boolean | null;
          schedule_preference?: string | null;
          last_cleaning?: string | null;
          requested_frequency?: string | null;
          maintenance_frequency?: string | null;
          urgency_level?: string | null;
          preferred_contact?: string | null;
          consent?: boolean | null;
          photos?: Json;
          message?: string | null;
          notes?: string | null;
          assigned_user?: string | null;
          next_action?: string | null;
          next_due_at?: string | null;
          last_intervention_at?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          landing_page?: string | null;
          service_source?: string | null;
          zone_source?: string | null;
          created_at?: string;
          updated_at?: string;
          next_action_date?: string | null;
          converted_client_id?: string | null;
          address?: string | null;
          filter_type?: string | null;
          motor_type?: string | null;
        };
        Update: {
          id?: string;
          reference?: string | null;
          source?: string;
          status?: "new" | "contacted" | "qualified" | "quote_requested" | "quote_sent" | "won" | "lost";
          priority?: string | null;
          company_name?: string | null;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          business_type?: string | null;
          city?: string | null;
          postal_code?: string | null;
          need_type?: string | null;
          request_type?: string | null;
          installation_type?: string | null;
          hood_type?: string | null;
          hood_length?: string | null;
          filter_count?: number | null;
          duct_present?: boolean | null;
          duct_length?: string | null;
          motor_present?: boolean | null;
          soil_level?: string | null;
          accessibility?: string | null;
          night_intervention?: boolean | null;
          schedule_preference?: string | null;
          last_cleaning?: string | null;
          requested_frequency?: string | null;
          maintenance_frequency?: string | null;
          urgency_level?: string | null;
          preferred_contact?: string | null;
          consent?: boolean | null;
          photos?: Json;
          message?: string | null;
          notes?: string | null;
          assigned_user?: string | null;
          next_action?: string | null;
          next_due_at?: string | null;
          last_intervention_at?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          landing_page?: string | null;
          service_source?: string | null;
          zone_source?: string | null;
          created_at?: string;
          updated_at?: string;
          next_action_date?: string | null;
          converted_client_id?: string | null;
          address?: string | null;
          filter_type?: string | null;
          motor_type?: string | null;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          invoice_id: string;
          client_id: string;
          amount: number;
          paid_at: string;
          method: "cash" | "transfer" | "card" | "check" | "other";
          reference: string | null;
          note: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          client_id: string;
          amount: number;
          paid_at?: string;
          method?: "cash" | "transfer" | "card" | "check" | "other";
          reference?: string | null;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          client_id?: string;
          amount?: number;
          paid_at?: string;
          method?: "cash" | "transfer" | "card" | "check" | "other";
          reference?: string | null;
          note?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      providers: {
        Row: {
          id: string;
          name: string;
          company_name: string | null;
          phone: string | null;
          email: string | null;
          city: string | null;
          intervention_zone: string | null;
          specialty: string | null;
          cost_rate: number | null;
          status: "active" | "inactive";
          notes: string | null;
          created_at: string;
          updated_at: string;
          user_id: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          company_name?: string | null;
          phone?: string | null;
          email?: string | null;
          city?: string | null;
          intervention_zone?: string | null;
          specialty?: string | null;
          cost_rate?: number | null;
          status?: "active" | "inactive";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          company_name?: string | null;
          phone?: string | null;
          email?: string | null;
          city?: string | null;
          intervention_zone?: string | null;
          specialty?: string | null;
          cost_rate?: number | null;
          status?: "active" | "inactive";
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          user_id?: string | null;
        };
        Relationships: [];
      };
      quote_items: {
        Row: {
          id: string;
          quote_id: string;
          service_catalog_id: string | null;
          label: string;
          description: string | null;
          quantity: number;
          unit_price_ht: number;
          vat_rate: number;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          service_catalog_id?: string | null;
          label: string;
          description?: string | null;
          quantity?: number;
          unit_price_ht?: number;
          vat_rate?: number;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          service_catalog_id?: string | null;
          label?: string;
          description?: string | null;
          quantity?: number;
          unit_price_ht?: number;
          vat_rate?: number;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      quotes: {
        Row: {
          id: string;
          reference: string | null;
          client_id: string;
          lead_id: string | null;
          status: "draft" | "sent" | "accepted" | "rejected" | "expired";
          issued_at: string | null;
          valid_until: string | null;
          notes: string | null;
          subtotal_ht: number;
          vat_amount: number;
          total_ttc: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          installation_id: string | null;
          discount_ht: number;
          deposit_amount: number;
          payment_terms: string | null;
          converted_intervention_id: string | null;
        };
        Insert: {
          id?: string;
          reference?: string | null;
          client_id: string;
          lead_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "rejected" | "expired";
          issued_at?: string | null;
          valid_until?: string | null;
          notes?: string | null;
          subtotal_ht?: number;
          vat_amount?: number;
          total_ttc?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          installation_id?: string | null;
          discount_ht?: number;
          deposit_amount?: number;
          payment_terms?: string | null;
          converted_intervention_id?: string | null;
        };
        Update: {
          id?: string;
          reference?: string | null;
          client_id?: string;
          lead_id?: string | null;
          status?: "draft" | "sent" | "accepted" | "rejected" | "expired";
          issued_at?: string | null;
          valid_until?: string | null;
          notes?: string | null;
          subtotal_ht?: number;
          vat_amount?: number;
          total_ttc?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          installation_id?: string | null;
          discount_ht?: number;
          deposit_amount?: number;
          payment_terms?: string | null;
          converted_intervention_id?: string | null;
        };
        Relationships: [];
      };
      service_catalog: {
        Row: {
          id: string;
          code: string | null;
          label: string;
          description: string | null;
          unit: string;
          unit_price_ht: number;
          vat_rate: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code?: string | null;
          label: string;
          description?: string | null;
          unit?: string;
          unit_price_ht?: number;
          vat_rate?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string | null;
          label?: string;
          description?: string | null;
          unit?: string;
          unit_price_ht?: number;
          vat_rate?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      staff_profiles: {
        Row: {
          user_id: string;
          role: "admin" | "commercial" | "prestataire";
          display_name: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          role: "admin" | "commercial" | "prestataire";
          display_name?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          role?: "admin" | "commercial" | "prestataire";
          display_name?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      client_financial_summary: {
        Row: {
          client_id: string;
          total_invoiced: number;
          total_paid: number;
          amount_due: number;
          last_intervention_at: string | null;
          next_intervention_at: string | null;
        };
        Relationships: [];
      };
      invoice_balances: {
        Row: {
          invoice_id: string;
          client_id: string;
          number: string | null;
          total_ttc: number;
          amount_paid: number;
          amount_due: number;
          status: "unpaid" | "partially_paid" | "paid" | "overdue" | "cancelled";
          due_at: string | null;
          issued_at: string;
        };
        Relationships: [];
      };
      provider_interventions: {
        Row: {
          id: string;
          reference: string | null;
          client_id: string;
          installation_id: string | null;
          provider_id: string | null;
          scheduled_date: string | null;
          time_slot: string | null;
          start_time: string | null;
          end_time: string | null;
          service_type: string | null;
          status: "to_plan" | "planned" | "in_progress" | "completed" | "cancelled";
          description: string | null;
          notes: string | null;
          address: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: {
      activity_type: "CLIENT_CREATED" | "QUOTE_CREATED" | "QUOTE_SENT" | "QUOTE_ACCEPTED" | "INTERVENTION_CREATED" | "INTERVENTION_COMPLETED" | "PHOTO_UPLOADED" | "INVOICE_CREATED" | "PAYMENT_RECEIVED" | "LEAD_CONVERTED" | "NOTE_ADDED" | "STATUS_CHANGED";
      client_status: "active" | "inactive" | "archived";
      document_type: "quote" | "invoice" | "report" | "contract" | "photo" | "other";
      intervention_status: "to_plan" | "planned" | "in_progress" | "completed" | "cancelled";
      invoice_status: "unpaid" | "partially_paid" | "paid" | "overdue" | "cancelled";
      lead_status: "new" | "contacted" | "qualified" | "quote_requested" | "quote_sent" | "won" | "lost";
      payment_method: "cash" | "transfer" | "card" | "check" | "other";
      photo_kind: "before" | "after" | "technical";
      provider_status: "active" | "inactive";
      quote_status: "draft" | "sent" | "accepted" | "rejected" | "expired";
      staff_role: "admin" | "commercial" | "prestataire";
    };
    CompositeTypes: Record<string, never>;
  };
};
