import { BrowserRouter, Link, NavLink, Route, Routes, useParams } from "react-router-dom";
import { Activity, ArrowUpRight, Bell, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck, Clock3, FileText, HardHat, LayoutDashboard, Receipt, Users, Wallet, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { clients, clientName, euro, installations, interventions, invoices, leads, payments, providers, quotes, type InvoiceStatus, type LeadStatus, type WorkStatus } from "@/lib/demo/data";

const nav = [
  ["/", "Tableau de bord", LayoutDashboard],
  ["/prospects", "Prospects", Users],
  ["/clients", "Clients", Building2],
  ["/interventions", "Interventions", Wrench],
  ["/devis", "Devis", FileText],
  ["/factures", "Factures", Receipt],
  ["/paiements", "Paiements", Wallet],
  ["/prestataires", "Prestataires", HardHat],
] as const;

const leadTone: Record<LeadStatus, "default" | "accent" | "success" | "warning"> = { new: "accent", contacted: "default", qualified: "accent", quote_sent: "warning", won: "success" };
const leadLabel: Record<LeadStatus, string> = { new: "Nouveau", contacted: "Contacté", qualified: "Qualifié", quote_sent: "Devis envoyé", won: "Gagné" };
const invoiceTone: Record<InvoiceStatus, "success" | "warning" | "danger"> = { paid: "success", partial: "warning", overdue: "danger" };
const invoiceLabel: Record<InvoiceStatus, string> = { paid: "Payée", partial: "Partielle", overdue: "En retard" };

function Status({ status, kind }: { status: LeadStatus | InvoiceStatus | WorkStatus; kind: "lead" | "invoice" | "work" }) {
  if (kind === "lead") return <Badge variant={leadTone[status as LeadStatus]}>{leadLabel[status as LeadStatus]}</Badge>;
  if (kind === "invoice") return <Badge variant={invoiceTone[status as InvoiceStatus]}>{invoiceLabel[status as InvoiceStatus]}</Badge>;
  return <Badge variant={status === "completed" ? "success" : "accent"}>{status === "completed" ? "Terminée" : "Planifiée"}</Badge>;
}

function Shell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-background">
    <div className="sticky top-0 z-30 flex h-8 items-center justify-center bg-[oklch(0.18_0.035_220)] px-3 text-[11px] font-medium tracking-wide text-white/80">Prototype de démonstration <span className="mx-2 text-teal-300">—</span> SalisCRM · Salis 3 Hottes</div>
    <div className="flex min-h-[calc(100vh-2rem)]">
      <aside className="hidden w-64 shrink-0 flex-col bg-sidebar p-4 text-sidebar-foreground md:flex">
        <Link to="/" className="mb-9 px-3 pt-3"><p className="font-serif text-2xl leading-none text-white">Salis<span className="text-teal-300">CRM</span></p><p className="mt-2 text-[10px] font-bold tracking-[.18em] text-teal-300 uppercase">Salis 3 Hottes</p></Link>
        <nav className="space-y-1">{nav.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === "/"} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${isActive ? "bg-white/12 text-white shadow-sm" : "text-white/60 hover:bg-white/7 hover:text-white"}`}><Icon className="size-4" />{label}</NavLink>)}</nav>
        <div className="mt-auto rounded-xl border border-white/10 bg-white/5 p-3"><div className="flex items-center gap-2"><div className="flex size-8 items-center justify-center rounded-full bg-teal-500 font-semibold text-white">SD</div><div><p className="text-xs font-semibold text-white">Sophie Durand</p><p className="text-[10px] text-white/50">Direction</p></div></div></div>
      </aside>
      <main className="min-w-0 flex-1"><header className="flex h-18 items-center justify-between border-b border-border bg-card/80 px-5 backdrop-blur md:px-9"><div><p className="text-xs font-semibold tracking-[.16em] text-teal-700 uppercase">Salis 3 Hottes</p><p className="text-sm text-muted-foreground">Mardi 8 septembre 2026</p></div><div className="flex items-center gap-3"><button className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><Bell className="size-5" /></button><div className="hidden text-right sm:block"><p className="text-sm font-semibold">Sophie Durand</p><p className="text-xs text-muted-foreground">Direction générale</p></div><div className="flex size-9 items-center justify-center rounded-full bg-ink text-sm font-bold text-white">SD</div></div></header><div className="mx-auto max-w-7xl p-5 md:p-9">{children}</div></main>
    </div>
  </div>;
}

function PageTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
  return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-teal-700 uppercase">{eyebrow}</p><h1 className="mt-1 font-serif text-3xl font-semibold tracking-tight text-ink md:text-4xl">{title}</h1></div>{children}</div>;
}
function Kpi({ label, value, detail, icon: Icon, tone = "teal" }: { label: string; value: string; detail: string; icon: typeof Wallet; tone?: "teal" | "navy" | "amber" | "rose" }) {
  const tones = { teal: "bg-teal-50 text-teal-700", navy: "bg-slate-100 text-slate-700", amber: "bg-amber-50 text-amber-700", rose: "bg-rose-50 text-rose-700" };
  return <Card className="overflow-hidden border-0 shadow-[0_10px_30px_-18px_rgba(15,23,42,.32)]"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold tracking-wide text-muted-foreground uppercase">{label}</p><p className="mt-2 text-2xl font-bold tracking-tight text-ink">{value}</p></div><div className={`rounded-xl p-2.5 ${tones[tone]}`}><Icon className="size-5" /></div></div><p className="mt-3 text-xs text-muted-foreground">{detail}</p></CardContent></Card>;
}
function Dashboard() {
  return <><PageTitle eyebrow="Vue d'ensemble" title="Bonjour Sophie."><Button variant="accent"><CalendarDays className="size-4" />Planifier une intervention</Button></PageTitle>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="CA encaissé — septembre" value="18 940 €" detail="↗ +18,4 % vs. août" icon={CircleDollarSign}/><Kpi label="À encaisser" value="3 600 €" detail="2 factures nécessitent une relance" icon={Wallet} tone="amber"/><Kpi label="Interventions à venir" value="4" detail="Prochaine : mardi 16 septembre" icon={CalendarDays} tone="navy"/><Kpi label="Taux de conversion" value="68 %" detail="↗ +6 pts sur les 30 derniers jours" icon={ArrowUpRight} tone="teal"/></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>À traiter aujourd'hui</CardTitle><p className="mt-1 text-xs text-muted-foreground">Les prochaines actions qui font avancer le pipeline.</p></div><Link className="text-xs font-semibold text-teal-700" to="/prospects">Voir tout</Link></CardHeader><CardContent className="divide-y divide-border p-0">{leads.slice(0, 4).map((lead) => <Link to={`/prospects/${lead.id}`} key={lead.id} className="flex items-center gap-3 px-5 py-4 transition hover:bg-muted/50"><div className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-teal-50 font-semibold text-teal-700">{lead.company.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{lead.company}</p><p className="truncate text-xs text-muted-foreground">{lead.note}</p></div><Status kind="lead" status={lead.status}/><ChevronRight className="size-4 text-muted-foreground"/></Link>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Interventions prochaines</CardTitle></CardHeader><CardContent className="space-y-4">{interventions.filter(i => i.status === "planned").slice(0, 3).map((item) => <Link key={item.id} to={`/interventions/${item.id}`} className="flex gap-3"><div className="flex h-11 w-11 shrink-0 flex-col items-center justify-center rounded-lg bg-slate-100 text-slate-700"><span className="text-xs font-bold">{item.date.slice(0,2)}</span><span className="text-[9px]">SEP</span></div><div><p className="text-sm font-semibold">{clientName(item.clientId)}</p><p className="text-xs text-muted-foreground">{item.title}</p><p className="mt-1 text-xs font-medium text-teal-700">{item.date.split("·")[1]} · {item.technician}</p></div></Link>)}</CardContent></Card></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Factures à relancer</CardTitle><Link className="text-xs font-semibold text-teal-700" to="/factures">Gérer les factures</Link></CardHeader><CardContent className="p-0"><Table headers={["Facture", "Client", "Échéance", "Reste dû", ""]}>{invoices.filter(i => i.remaining).map(i => <tr key={i.id} className="border-t border-border"><Td><b>{i.id.toUpperCase()}</b></Td><Td>{clientName(i.clientId)}</Td><Td className={i.status === "overdue" ? "text-rose-600" : ""}>{i.due}</Td><Td><b>{euro(i.remaining)}</b></Td><Td><Status kind="invoice" status={i.status}/></Td></tr>)}</Table></CardContent></Card>
    <Card><CardHeader><CardTitle>Activité récente</CardTitle></CardHeader><CardContent className="space-y-4">{["Paiement reçu — La Verrière Montmartre", "Devis D-2026-044 envoyé à Hôtel des Arts", "Intervention terminée — Relais Gourmet Dijon", "Nouveau prospect : Bistrot des Ternes"].map((text, index) => <div className="flex gap-3" key={text}><div className="mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full bg-teal-50"><Activity className="size-3.5 text-teal-700"/></div><div><p className="text-sm">{text}</p><p className="text-xs text-muted-foreground">{["Il y a 25 min", "Il y a 2 h", "Hier à 17:42", "Hier à 11:18"][index]}</p></div></div>)}</CardContent></Card></div></>;
}
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-muted/60 text-[11px] font-bold tracking-wide text-muted-foreground uppercase"><tr>{headers.map(h => <th className="px-5 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }
function Td({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <td className={`px-5 py-3.5 ${className}`}>{children}</td>; }
function Leads() { return <><PageTitle eyebrow="Développement commercial" title="Prospects"><Button variant="accent"><Users className="size-4"/>Nouveau prospect</Button></PageTitle><Card><Table headers={["Entreprise", "Contact", "Origine", "Potentiel", "Statut", ""]}>{leads.map(l => <tr className="border-t border-border hover:bg-muted/40" key={l.id}><Td><Link className="font-semibold hover:text-teal-700" to={`/prospects/${l.id}`}>{l.company}</Link><p className="text-xs text-muted-foreground">{l.city}</p></Td><Td>{l.contact}<p className="text-xs text-muted-foreground">{l.phone}</p></Td><Td>{l.source}</Td><Td className="font-semibold">{euro(l.value)}</Td><Td><Status kind="lead" status={l.status}/></Td><Td><Link to={`/prospects/${l.id}`}><ChevronRight className="size-4 text-muted-foreground"/></Link></Td></tr>)}</Table></Card></>; }
function Clients() { return <><PageTitle eyebrow="Portefeuille" title="Clients"><Button variant="accent"><Building2 className="size-4"/>Nouveau client</Button></PageTitle><div className="mb-5 flex gap-3"><div className="rounded-lg border border-border bg-card px-4 py-2 text-sm"><b>7</b> <span className="text-muted-foreground">clients actifs</span></div><div className="rounded-lg border border-border bg-card px-4 py-2 text-sm"><b>28 120 €</b> <span className="text-muted-foreground">CA annuel</span></div></div><Card><Table headers={["Client", "Ville", "Contrat", "Installations", "CA annuel", ""]}>{clients.map(c => <tr className="border-t border-border hover:bg-muted/40" key={c.id}><Td><Link className="font-semibold hover:text-teal-700" to={`/clients/${c.id}`}>{c.name}</Link><p className="text-xs text-muted-foreground">{c.contact}</p></Td><Td>{c.city}</Td><Td>{c.contract}</Td><Td>{c.installations}</Td><Td className="font-semibold">{euro(c.revenue)}</Td><Td><Link to={`/clients/${c.id}`}><ChevronRight className="size-4 text-muted-foreground"/></Link></Td></tr>)}</Table></Card></>; }
function Detail({ type }: { type: "client" | "lead" }) {
  const { id } = useParams();
  if (type === "client") {
    const client = clients.find((entry) => entry.id === id);
    if (!client) return <p>Élément introuvable.</p>;
    const localInstalls = installations.filter((entry) => entry.clientId === client.id);
    return <EntityLayout back="/clients" eyebrow="Fiche client" title={client.name} subtitle={client.city} action="Planifier une intervention" contact={client.contact} phone={client.phone} email={client.email} address={client.address}><Card><CardHeader><CardTitle>Installations suivies</CardTitle></CardHeader><CardContent className="grid gap-3">{localInstalls.map((installation) => <div key={installation.id} className="rounded-xl border border-border p-4"><p className="font-semibold">{installation.label}</p><p className="mt-2 text-sm text-muted-foreground">{installation.hood} · {installation.filters}</p><p className="text-sm text-muted-foreground">{installation.duct} · {installation.motor}</p></div>)}</CardContent></Card></EntityLayout>;
  }
  const lead = leads.find((entry) => entry.id === id);
  if (!lead) return <p>Élément introuvable.</p>;
  return <EntityLayout back="/prospects" eyebrow="Prospect" title={lead.company} subtitle={`${lead.city} · ${lead.contact}`} action="Créer un devis" contact={lead.contact} phone={lead.phone}><Card><CardHeader><CardTitle>Qualification commerciale</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Origine</span><b>{lead.source}</b></div><div className="flex justify-between"><span className="text-muted-foreground">Potentiel estimé</span><b>{euro(lead.value)}</b></div><div className="rounded-xl bg-teal-50 p-4 text-teal-900">{lead.note}</div></CardContent></Card></EntityLayout>;
}
function EntityLayout({ back, eyebrow, title, subtitle, action, contact, phone, email, address, children }: { back: string; eyebrow: string; title: string; subtitle: string; action: string; contact: string; phone: string; email?: string; address?: string; children: React.ReactNode }) { return <><Link to={back} className="text-sm font-medium text-teal-700">← Retour à la liste</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-teal-700 uppercase">{eyebrow}</p><h1 className="mt-1 font-serif text-3xl font-semibold">{title}</h1><p className="mt-1 text-muted-foreground">{subtitle}</p></div><Button variant="accent">{action}</Button></div><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_2fr]"><Card><CardHeader><CardTitle>Coordonnées</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><span className="text-muted-foreground">Contact</span><br/><b>{contact}</b></p><p><span className="text-muted-foreground">Téléphone</span><br/>{phone}</p>{email && <p><span className="text-muted-foreground">Email</span><br/>{email}</p>}{address && <p><span className="text-muted-foreground">Adresse</span><br/>{address}</p>}</CardContent></Card><div><div className="mb-4 flex gap-5 border-b border-border text-sm font-medium"><span className="border-b-2 border-teal-600 px-1 pb-3 text-teal-700">Vue d'ensemble</span><span className="px-1 pb-3 text-muted-foreground">Historique</span><span className="px-1 pb-3 text-muted-foreground">Documents</span></div>{children}</div></div></>; }
function WorkList() { return <><PageTitle eyebrow="Opérations" title="Interventions"><Button variant="accent"><CalendarDays className="size-4"/>Planifier</Button></PageTitle><Card><Table headers={["Date", "Client", "Intervention", "Intervenant", "Montant", "Statut"]}>{interventions.map(i => <tr className="border-t border-border hover:bg-muted/40" key={i.id}><Td><Link className="font-semibold hover:text-teal-700" to={`/interventions/${i.id}`}>{i.date}</Link></Td><Td>{clientName(i.clientId)}</Td><Td>{i.title}</Td><Td>{i.technician}</Td><Td>{euro(i.amount)}</Td><Td><Status kind="work" status={i.status}/></Td></tr>)}</Table></Card></>; }
function WorkDetail() { const { id } = useParams(); const item = interventions.find(x => x.id === id); if (!item) return <p>Intervention introuvable.</p>; return <><Link to="/interventions" className="text-sm font-medium text-teal-700">← Retour aux interventions</Link><PageTitle eyebrow="Intervention planifiée" title={clientName(item.clientId)}><Status kind="work" status={item.status}/></PageTitle><div className="grid gap-6 md:grid-cols-2"><Card><CardHeader><CardTitle>Informations de mission</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><p><span className="text-muted-foreground">Créneau</span><br/><b>{item.date}</b></p><p><span className="text-muted-foreground">Prestation</span><br/>{item.title}</p><p><span className="text-muted-foreground">Équipe</span><br/>{item.technician} · {item.duration}</p></CardContent></Card><Card><CardHeader><CardTitle>Checklist opérationnelle</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{["Sécurisation de la zone", "Dégraissage hotte et filtres", "Nettoyage des conduits", "Photos et certificat de passage"].map((t, n) => <div className="flex items-center gap-3" key={t}><CheckCircle2 className={`size-5 ${item.status === "completed" || n === 0 ? "text-teal-600" : "text-border"}`}/>{t}</div>)}</CardContent></Card></div></>; }
function Documents({ kind }: { kind: "quote" | "invoice" }) { const isQuote = kind === "quote"; return <><PageTitle eyebrow={isQuote ? "Commercial" : "Facturation"} title={isQuote ? "Devis" : "Factures"}><Button variant="accent"><FileText className="size-4"/>Nouveau {isQuote ? "devis" : "facture"}</Button></PageTitle><Card><Table headers={[isQuote ? "Devis" : "Facture", "Client", "Date", isQuote ? "Validité" : "Échéance", "Montant", "Statut"]}>{isQuote ? quotes.map((row) => <QuoteRow key={row.id} row={row}/>) : invoices.map((row) => <InvoiceRow key={row.id} row={row}/>)}</Table></Card></>; }
function QuoteRow({ row }: { row: (typeof quotes)[number] }) { return <tr className="border-t border-border hover:bg-muted/40"><Td><Link className="font-semibold hover:text-teal-700" to={`/devis/${row.id}`}>{row.id.toUpperCase()}</Link></Td><Td>{clientName(row.clientId)}</Td><Td>{row.date}</Td><Td>{row.valid}</Td><Td className="font-semibold">{euro(row.total)}</Td><Td><Badge variant={row.status === "accepted" ? "success" : row.status === "sent" ? "accent" : "default"}>{row.status === "accepted" ? "Accepté" : row.status === "sent" ? "Envoyé" : "Brouillon"}</Badge></Td></tr>; }
function InvoiceRow({ row }: { row: (typeof invoices)[number] }) { return <tr className="border-t border-border hover:bg-muted/40"><Td><Link className="font-semibold hover:text-teal-700" to={`/factures/${row.id}`}>{row.id.toUpperCase()}</Link></Td><Td>{clientName(row.clientId)}</Td><Td>{row.issued}</Td><Td>{row.due}</Td><Td className="font-semibold">{euro(row.total)}</Td><Td><Status kind="invoice" status={row.status}/></Td></tr>; }
function DocumentDetail({ kind }: { kind: "quote" | "invoice" }) { const { id } = useParams(); if (kind === "quote") { const quote = quotes.find((entry) => entry.id === id); if (!quote) return <p>Document introuvable.</p>; return <DocumentPaper back="/devis" eyebrow="Devis client" item={quote} lines={quote.items} date={quote.date}/>; } const invoice = invoices.find((entry) => entry.id === id); if (!invoice) return <p>Document introuvable.</p>; return <DocumentPaper back="/factures" eyebrow="Facture client" item={invoice} lines={["Prestation de nettoyage et entretien extraction"]} date={invoice.issued} remaining={invoice.remaining}/>; }
function DocumentPaper({ back, eyebrow, item, lines, date, remaining }: { back: string; eyebrow: string; item: { id: string; clientId: string; total: number }; lines: string[]; date: string; remaining?: number }) { return <><Link to={back} className="text-sm font-medium text-teal-700">← Retour aux documents</Link><PageTitle eyebrow={eyebrow} title={item.id.toUpperCase()}><Button variant="outline">Télécharger PDF</Button></PageTitle><Card className="max-w-3xl"><CardContent className="p-7"><div className="flex justify-between border-b border-border pb-6"><div><p className="font-serif text-2xl font-semibold">SalisCRM</p><p className="text-sm text-muted-foreground">Salis 3 Hottes</p></div><div className="text-right text-sm"><b>{clientName(item.clientId)}</b><p className="text-muted-foreground">{date}</p></div></div><div className="divide-y divide-border py-5">{lines.map((line, index) => <div className="flex justify-between py-3 text-sm" key={line}><span>{line}</span><span>{euro(index === lines.length - 1 ? item.total : 0)}</span></div>)}</div><div className="ml-auto max-w-xs border-t border-ink pt-4"><div className="flex justify-between text-lg font-bold"><span>Total TTC</span><span>{euro(item.total)}</span></div>{remaining !== undefined && <p className="mt-2 text-sm text-muted-foreground">Reste à régler : <b className="text-ink">{euro(remaining)}</b></p>}</div></CardContent></Card></>; }
function Payments() { return <><PageTitle eyebrow="Trésorerie" title="Paiements"><Button variant="accent"><Wallet className="size-4"/>Enregistrer un paiement</Button></PageTitle><div className="mb-6 grid gap-4 sm:grid-cols-3"><Kpi label="Encaissé ce mois" value="6 520 €" detail="6 règlements enregistrés" icon={Wallet}/><Kpi label="À relancer" value="3 600 €" detail="Deux échéances dépassées" icon={Clock3} tone="rose"/><Kpi label="Délai moyen" value="18 jours" detail="↘ 3 jours vs. août" icon={ClipboardCheck} tone="navy"/></div><Card><Table headers={["Date", "Client", "Facture", "Mode", "Montant"]}>{payments.map(p => <tr className="border-t border-border" key={p.id}><Td>{p.date}</Td><Td className="font-semibold">{clientName(p.clientId)}</Td><Td>{p.invoiceId.toUpperCase()}</Td><Td>{p.method}</Td><Td className="font-semibold text-teal-700">+ {euro(p.amount)}</Td></tr>)}</Table></Card></>; }
function Providers() { return <><PageTitle eyebrow="Réseau opérationnel" title="Prestataires"><Button variant="accent"><HardHat className="size-4"/>Ajouter un prestataire</Button></PageTitle><div className="grid gap-5 lg:grid-cols-3">{providers.map(p => <Card key={p.id}><CardContent className="p-5"><div className="flex items-start justify-between"><div className="flex size-11 items-center justify-center rounded-xl bg-slate-100 text-slate-700"><HardHat className="size-5"/></div><Badge variant={p.status === "Disponible" ? "success" : "accent"}>{p.status}</Badge></div><h2 className="mt-5 font-semibold">{p.name}</h2><p className="text-sm text-muted-foreground">{p.speciality}</p><div className="mt-5 grid grid-cols-2 gap-3 border-t border-border pt-4 text-sm"><div><p className="text-muted-foreground">Zone</p><p className="font-medium">{p.area}</p></div><div><p className="text-muted-foreground">Évaluation</p><p className="font-medium text-teal-700">★ {p.rating} · {p.jobs} missions</p></div></div></CardContent></Card>)}</div></>; }
export function DemoApp() { return <BrowserRouter><Shell><Routes><Route path="/" element={<Dashboard/>}/><Route path="/prospects" element={<Leads/>}/><Route path="/prospects/:id" element={<Detail type="lead"/>}/><Route path="/clients" element={<Clients/>}/><Route path="/clients/:id" element={<Detail type="client"/>}/><Route path="/interventions" element={<WorkList/>}/><Route path="/interventions/:id" element={<WorkDetail/>}/><Route path="/devis" element={<Documents kind="quote"/>}/><Route path="/devis/:id" element={<DocumentDetail kind="quote"/>}/><Route path="/factures" element={<Documents kind="invoice"/>}/><Route path="/factures/:id" element={<DocumentDetail kind="invoice"/>}/><Route path="/paiements" element={<Payments/>}/><Route path="/prestataires" element={<Providers/>}/></Routes></Shell></BrowserRouter>; }
